### ISSUE TITLE
Ashley F. Orientation

### ISSUE THREAD

**Issue by dkbaldwin** [inDevelopme/indevelopme-coaching-publications#81]
# Orientation
We feel that professional development is like starting a journey into fitness or building your first player profile in NBA 2K. That is why JustAskDavidB focuses on setting up a solid foundation for all its players. 

## Consultation
You get four meetings free as part of the orientation process. The first one is how you got here in the first place. And the last one covers the conclusion of the orientation process. Check these off as you complete each one. 

- [ ] Introduction Consultation: Your professional needs and desires.
- [ ] Office Hour: Meeting Others Like You
- [ ] Debriefing: Are you staying in the program?

## Articles to Read
- [ ] [JustAskDavidB Explained](https://www.developme10x.com/indevelopme/justaskdavidb/bootcamp)
- [ ] [Published Works](https://medium.com/indevelopme-tech-coaching-program)

## Listen to Podcast
We offer a podcast that intended to help programmers, career shifters, and entreprenuers progress in their professional career. We have struggled to identify the most relevant material for this bootcamp. 

For that reason, you must listen to ***ALL*** of the first 18 episodes of the podcast because every episode will apply to your professional career in some form. This take about 6-9 hours ( 5 days worth of traffic)

### ***Platform Used for Podcast***
Check off the platform you used to listen to the podcast:
- [ ] [Spotify](https://open.spotify.com/show/7altHV6BJYSMS4TlbsbdZy?si=3c24a79eb22540c1)
- [ ] [Apple Podcast](https://podcasts.apple.com/us/podcast/justaskdavidb/id1681610153)
- [ ] [ListenNotes](https://www.listennotes.com/podcasts/justaskdavidb-developme10x-8G4BIveuw7R/)

### ***Feedback About Podcast Episodes***
- [ ] Provided a comment in this issue ticket about the five (5) of the most relevant episodes
- [ ] Provided a review on the podcast platform to help others
 
## Programs to install on your computer
- [ ] [Pycharm Community Version ](https://www.jetbrains.com/pycharm/download)
- [ ] [Docker Desktop](https://www.docker.com/products/docker-desktop/)
- [ ] [Github Desktop](https://desktop.github.com/)

## Accounts to create
Create accounts on the following platforms:

- [ ] [Github account](www.github.com) 
- [ ] [Linkedin](www.linkedin.com)
- [ ] [Slack](www.slack.com) (we will add you to the slack group later)
- [ ] [Medium](www.medium.com) (free account only)

## Learning Management System
You only need one of these LMS systems and its based on your professional interest. 
- [ ] Programmers Guild need a monthly subscription to [Pluralsight](www.pluralsight.com) (premium)
- [ ] DevOps Guild need a monthly subscription to install [ACloudGuru](www.acloudguru.com) (premium plus)

## Mobile App (optional)
It is recommended that you install these applications on your phone for easy collaboration.
- [ ] Github
- [ ] Slack
- [ ] Linkedin
- [ ] Pluralsight / Acloudguru

It is important for you to see some of the cool things we do in AI/ML. And we want you to have an even better idea of how you would fit into the JustAskDavidB program. So here are some short Generative AI videos we have created about our target audience.

## Important Quests for Knowledge Transfer
You must complete all these activities as part of your orientation. They will teach you fundamentatl concepts about 

### ***Generative AI Quest***
- [ ] [Asking the Right Question](https://youtu.be/wK7WMfq1Ja0?si=KmssJdFYOH56i2Gs)
- [ ] [Meet Tommy](https://youtu.be/Z8R1AtJpcWQ?si=xyzz3TRF2MNLYUrn)
- [ ] [What is the Cloud by AI Trevor Noah](https://www.youtube.com/watch?v=LbbE8UV0EWo&t=10s)
- [ ] [Meet Maya](https://youtube.com/shorts/siSr8300N7s?si=3mXJyUcfduo1-CJD)

### ***Issue Template Quest***
- [ ] [Reviewed Issue Ticket](https://github.com/inDevelopme/justaskdavidb/issues/72)
- [ ] [Reviewed Pull Request-1](https://github.com/inDevelopme/justaskdavidb/pull/74)
- [ ] [Reviewed Pull Request-2](https://github.com/inDevelopme/justaskdavidb/pull/79)

### ***Markdown Documentation Quest***
- [ ] [Reviewed Issue Ticket](https://github.com/inDevelopme/justaskdavidb/issues/70)

### ***What is an IDE***
- [ ] [Review Issue Ticket](https://github.com/inDevelopme/justaskdavidb/issues/69)
- [ ] [Review Powerpoint Presentation](https://www.linkedin.com/posts/developme10x_what-is-an-ide-activity-7186725214083248128-RFvW)

### ***Linux Command Quest***
- [ ] [Reviewed Issue Ticket](https://github.com/inDevelopme/justaskdavidb/issues/65)
- [ ] [Watched Linkedin Video](https://www.linkedin.com/posts/indevelopme_indevelopme-justaskdavidb-developme10x-activity-7232098696102862849-Q3V3)

### ***Git Quest***
- [ ] [Review: Mac Users need to know how to install git](https://github.com/inDevelopme/justaskdavidb/issues/68)

Estimated Time: 13 - 21 hours
